# _config.yml

# Site settings
title: army2cyber
description: A blog documenting my journey from military service to a career in cybersecurity.
url: https://onyx998.github.io/army2cyber/ # Replace with your GitHub Pages URL
baseurl: "" # Leave empty if using the root domain

# Author settings
author:
  email: onyx99924@proton.me # Replace with your email

# Build settings
markdown: kramdown
theme: minima # You can change this to any other theme you prefer

# Social media links
social:
  twitter: your_twitter_handle # Replace with your Twitter handle
  github: your_github_username # Replace with your GitHub username
  linkedin: your_linkedin_profile # Replace with your LinkedIn profile

# Navigation settings
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact

# Permalinks
permalink: pretty

# Exclude files and directories from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
