title: army2cyber
description: A blog documenting my journey from military service to a career in cybersecurity.
url: https://onyx998.github.io/army2cyber/ # Replace with your GitHub Pages URL
baseurl: "" # Leave empty if using the root domain
theme: minima


sass:
  style: compressed
